apiVersion: s3.aws.crossplane.io/v1beta1
kind: Bucket
metadata:
  name: demo-s3-bucket
  annotations:
    crossplane.io/external-name: crossplane-example-repl-dest
spec:
  deletionPolicy: Delete
  forProvider:
    acl: private
    locationConstraint: us-east-1
    paymentConfiguration:
      payer: BucketOwner
    serverSideEncryptionConfiguration:
      rules:
        - applyServerSideEncryptionByDefault:
            sseAlgorithm: AES256
    versioningConfiguration:
      status: Enabled
  providerConfigRef:
    name: localstack